### ISSUE TITLE
Liveness / readiness for our components

### ISSUE THREAD

**Issue by framiere** [confluentinc/cp-helm-charts#109]
I see only a single liveness probe for ZK.
Shouldn't we add liveness and readyness for all components ?

example for kafka
```yml
        livenessProbe:
          exec:
            command:
              - sh
              - -ec
              - /usr/bin/jps | /bin/grep -q SupportedKafka
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          timeoutSeconds: 5
```

for zk

```yml
        livenessProbe:
          exec:
            command: ['/bin/bash', '-c', 'echo "ruok" | nc -w 2 -q 2 localhost 2181 | grep imok']
          initialDelaySeconds: 1
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 2181
          initialDelaySeconds: 30
          timeoutSeconds: 5
```

**Comment by pavel-agarkov** [comment]
Even if you are not going to include probes by default - they might be optional.  
At least let's collect all the ideas and best practices somewhere so people can for example vote for them.  
For KSQL I've tried [this](https://docs.confluent.io/current/ksql/docs/operations.html#healthchecks) but nothing actually worked since rest api turned off when queries file specified and `ksql-print-metrics` script is present in `cp-ksql-server` image but looks like some `.jar`s are missing...
For Connect I use the following probe:
```yaml
livenessProbe:
  exec:
    command:
      - bash
      - -c
      - curl -v --silent http://localhost:8083/connectors/PUT_CONNECTOR_NAME_HERE/status 2>&1 | grep \"RUNNING.*RUNNING\" 1>/dev/null
```
