### ISSUE TITLE
How to create topics during startup?

### ISSUE THREAD

**Issue by pratapagiri** [confluentinc/cp-helm-charts#164]
Could you please let us know how to create topics during startup of the kafka/zookeeper containers?

**Comment by mixja** [comment]
You can define a configmap and job that creates your topics for you:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cbp-confluent-configmap
data:
  topics: topic1,topic2,topic3
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: cbp-confluent-topics
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: topics
        image: confluentinc/cp-kafka:5.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: ZOOKEEPERS
          value: cbp-confluent-cp-zookeeper:2181
        - name: TOPICS
          valueFrom:
            configMapKeyRef:
              name: cbp-confluent-configmap
              key: topics
        command:
        - bash
        - -c
        - |
          IFS=',' read -ra topics <<< "$TOPICS"
          for topic in ${topics[@]}
          do
            echo "Creating topic $topic..."
            kafka-topics --zookeeper $ZOOKEEPERS --create --topic $topic --partitions 3 --replication-factor 3 --if-not-exists
          done
```
