### ISSUE TITLE
Expose Kafka broker for local dev

### ISSUE THREAD

**Issue by milanvdm** [confluentinc/cp-helm-charts#192]
Currently the BrokerService is not exposed to the outside world (https://github.com/confluentinc/cp-helm-charts/blob/master/charts/cp-kafka/templates/service.yaml)
For local development on minikube, it would be handy to be able to run your code against the cluster from the outside.

Would it be possible to also include the setting to expose the broker?

**Comment by mirkoprescha** [comment]
I use these settings to configure external broker access:
Providing optional values file: **my-values-local-broker-access.yaml**
```
cp-kafka:
  customEnv:
    MY_ADVERTISED_LISTENER_HOST: ""
  configurationOverrides:
    "advertised.listeners": |-
      EXTERNAL://$(MY_ADVERTISED_LISTENER_HOST):$((31090 + ${KAFKA_BROKER_ID}))
  nodeport:
    enabled: true
```

Use this config-file if env-variable *EXTERNAL_BROKER_ACCESS* is set to "YES":
```
if [ "$EXTERNAL_BROKER_ACCESS" == "YES" ]
then
    echo "creating confluent platform with external broker access. Set EXTERNAL_BROKER_ACCESS=NO if not required."
    MINIKUBE_IP=$(minikube ip)
    LOCAL_BROKER_ACCESS_CONFIG="-f my-values-local-broker-access.yaml --set cp-kafka.customEnv.MY_ADVERTISED_LISTENER_HOST=${MINIKUBE_IP}"
fi

helm upgrade --install --wait --timeout 600 "${RELEASE_NAME}" confluent/cp-helm-charts -f my-default-values.yaml $LOCAL_BROKER_ACCESS_CONFIG
```

With the **customEnv** I am forwarding dynamically the minikube-ip into the broker, which will use it to overwrite *KAFKA_ADVERTISED_LISTENERS*: 

![image](https://user-images.githubusercontent.com/8911986/49650527-b9f2c400-fa2c-11e8-8866-3bbe8193300d.png)
