### ISSUE TITLE
Kafka statefulSet will not start in minikube even with persistence: false

### ISSUE THREAD

**Issue by guilhemmarchand** [confluentinc/cp-helm-charts#216]
**Affects:**

Testing Confluent in Minikube with persistence set to false

**Issue:**

Even if persistence is set to false in values.yml, the Kafka brokers statefulSet will not start properly.

```
kubectl -n <namespace> describe statefulsets.apps <helm version name>
```

**Shows the volume issue:**

```
Events:
  Type     Reason        Age                   From                    Message
  ----     ------        ----                  ----                    -------
  Warning  FailedCreate  116s (x118 over 52m)  statefulset-controller  create Pod confluent-oss-v2-cp-kafka-0 in StatefulSet confluent-oss-v2-cp-kafka failed error: Pod "confluent-oss-v2-cp-kafka-0" is invalid: spec.containers[1].volumeMounts[0].name: Not found: "datadir-0"
```

Note that the Zookeeper statefulSet start correctly.

In minikube to get things working, I had to use persistence, modify values.yml to include:

```
cp-zookeeper:
  persistence:
    enabled: true
    dataDirStorageClass: "kafka-zookeeper"

cp-kafka:
  persistence:
    enabled: true
    storageClass: "kafka-broker"
```

Then creating storage classes for Minikube:

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-broker
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-zookeeper
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
```

- persistence: false should work and it is not the case for Kafka brokers
- A sample configuration for Minikube would help people getting it working

**Comment by lnardai** [comment]
I ran into the same issue using the official guide.
https://docs.confluent.io/current/installation/installing_cp/cp-helm-charts/docs/index.html#persistence

Managed to find a workaround. If you modify the **disksPerBroker** from the original 1 to zero, pods should start.
Example:
``` 
cp-kafka:
... 
persistence:
    enabled: false
    # storageClass: ""
    size: 5Gi
    disksPerBroker: 0
```

Error is located in this file: statefulset.yaml

`{{- range $k, $e := until $disksPerBroker }}`
