### ISSUE TITLE
cp-kafka requirements cp-zookeeper unbound dynamic pv

### ISSUE THREAD

**Issue by Aisuko** [confluentinc/cp-helm-charts#218]
Hi, I tried to deployed `cp-kafka` chart on my own kubernetes cluster, and I get error like this

```$ kubectl get pods
NAME                               READY   STATUS             RESTARTS   AGE
example2-cp-kafka-0                2/2     Running            3          3m
example2-cp-kafka-1                1/2     CrashLoopBackOff   2          3m
example2-cp-kafka-2                2/2     Running            3          3m
example2-cp-zookeeper-0            0/2     Pending            0          3m
nfs-provisioner-6bcb8dd785-q2x8m   1/1     Running            18         16d
```
and the `cp-zookeeper` pod descriptions below
```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  2m (x138 over 7m6s)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 4 times)
```
the chart's pvc status
```
persistentvolumeclaim/datadir-example-cp-zookeeper-0               Pending                                                                                       7m
persistentvolumeclaim/datalogdir-example-cp-zookeeper-0            Pending                                                                                       7m
```
The reason
```
Events:
  Type       Reason         Age               From                         Message
  ----       ------         ----              ----                         -------
  Normal     FailedBinding  3s (x9 over 94s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
Mounted By:  example-cp-zookeeper-0
```

So ,I was solved this by adding `dataDirStorageClass` and `dataLogDirStorageClass` to `values.yaml`'s cp-zookeeper to support dynamic pv.

```
## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  ## If true, install the cp-zookeeper chart alongside cp-kafka
  ## ref: ../cp-zookeeper
  enabled: true
  servers: 3
  persistence:
    enabled: true
    dataDirSize: 5Gi
    dataDirStorageClass: "example-nfs"
    dataLogDirSize: 5Gi
    dataLogDirStorageClass: "example-nfs"

  ## If the Zookeeper Chart is disabled a URL and port are required to connect
  url: ""
```
So, I think this may be an issue, please fix that.
