### ISSUE TITLE
Disabling of subcharts not working

### ISSUE THREAD

**Issue by florianrusch** [confluentinc/cp-helm-charts#224]
We are using `cp-helm-charts` as a dependency in our own helm chart:
`requirements.yaml`:
```yaml
dependencies:
- name: cp-helm-charts
  version: 0.1.0
  repository: https://confluentinc.github.io/cp-helm-charts/
```

In the `values.yaml` file of the chart we are trying to disable the kafka-connect, kafka-rest and the ksql-server:
```yaml
cp-helm-charts:
  cp-kafka:
    ...
  cp-zookeeper:
    ...
  cp-schema-registry:
    ...

  cp-kafka-rest:
    enabled: false

  cp-kafka-connect:
    enabled: false

  cp-ksql-server:
    enabled: false
```

If we try to deploy this, the three subcharts will still be deployed.
I've already checked the generated values with `helm --debug` which looks fine for me.

Does someone has an idea whats going on?

**Comment by florianrusch** [comment]
Interesting...this looks to be working:

```yaml
cp-helm-charts:
  cp-kafka:
    ...
  cp-zookeeper:
    ...
  cp-schema-registry:
    ...

cp-kafka-rest:
  enabled: false

cp-kafka-connect:
  enabled: false

cp-ksql-server:
  enabled: false
```

But why? `kafka-rest`, `kafka-connect` and `ksql-server` are dependencies of the `cp-helm-charts` chart. So the path should be `cp-helm-charts.cp-kafka-rest.enabled` or not?
