### ISSUE TITLE
JMX exporter port not exposed by services

### ISSUE THREAD

**Issue by gkocur** [confluentinc/cp-helm-charts#241]
The jmx exporter port in most charts (schema-registry, ksql-server etc) is not exposed by service. It makes it impossible to monitor it using prometheus operator and ServiceMonitor.

**Comment by qshao-pivotal** [comment]
It works with the prometheus installed through Helm chart... I'm under the impression that prometheus works with annotations not services...

**Comment by noderat** [comment]
@qshao-pivotal The new recommended path of using the prometheus-operator depends on services being exposed instead of the annotations.

@gkocur I've ran into this issue as well which we discovered late in the game and had to tweak manually post-deploy. I'm looking into creating a PR for this but I'm not sure if there is a common naming convention that the community has settled on for naming these services yet. Suggestions?

**Comment by qshao-pivotal** [comment]
Got it. Thanks a lot for the explanation. Add https://coreos.com/operators/prometheus/docs/latest/user-guides/running-exporters.html for reference.
Should it be 1 service per exporter container OR we could use one service for a cluster(e.g. 1 service for a 3 nodes kafka, 1 service for 3 nodes zookeeper, 1 for all kafka schema containers)?

No naming convention at this point yet... I would recommend putting services in `service.yaml`.
e.g. for zookeeper: 
https://github.com/confluentinc/cp-helm-charts/blob/master/charts/cp-zookeeper/templates/service.yaml

Name of service could be `{{ template "cp-zookeeper.fullname" . }}-exporter` if there's only 1 service is needed, `{{ template "cp-zookeeper.fullname" . }}-{0...N}-exporter` if 1 service per pod.

Also, I would recommend doing zookeeper only first, validate it before making changes to all charts.

**Comment by dojadop** [comment]
Another option is to add a secondary port on the existing services for each of the charts.  I did a proof of concept on the cp-kafka-connect chart and I call the port `metrics` which references the `prometheus.jmx.port` value

```
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka-connect.fullname" . }}
  labels:
    app: {{ template "cp-kafka-connect.name" . }}
    chart: {{ template "cp-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: kafka-connect
      port: {{ .Values.servicePort }}
    - name: metrics
      port: {{ .Values.prometheus.jmx.port }}
  selector:
    app: {{ template "cp-kafka-connect.name" . }}
    release: {{ .Release.Name }}
```

And then to monitor it with prometheus operator here is my ServiceMonitor definition
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: kafka-connect
spec:
  selector:
    matchLabels:
      release: kafka-connect
  endpoints:
    - port: metrics
```
