### ISSUE TITLE
How to start a single node kafka cluster

### ISSUE THREAD

**Issue by tobias-neubert** [confluentinc/cp-helm-charts#264]
Hi,

can anybody tell me how to start only one zookeeper and one kafka broker? Given the following values.yaml file in my helm chart I can enable/disable all components but the number of brokers/servers is not adjusted accordingly. What am I doing wrong here?

```yaml
cp-zookeeper:
  enabled: true
  servers: 1
cp-kafka:
  enabled: true
  brokers: 1
cp-schema-registry:
  enabled: false
cp-kafka-connect:
  enabled: false
cp-kafka-rest:
  enabled: false
cp-ksql-server:
  enabled: false
```

**Comment by jswoods** [comment]
@tobias-neubert I think this is what you want. I also found the namespacing confusing, but I think this is because the logic for the `enabled` boolean is done as a conditional around including the sub charts.

```
cp-helm-charts:
  cp-zookeeper:
    servers: 1
  cp-kafka:
    brokers: 1
cp-schema-registry:
  enabled: false
cp-kafka-connect:
  enabled: false
cp-kafka-rest:
  enabled: false
cp-ksql-server:
  enabled: false
```
