### ISSUE TITLE
Setting `broker` to 1 does change replica could for cp-kafka stateful-set

### ISSUE THREAD

**Issue by kevinkirkup** [confluentinc/cp-helm-charts#291]
If you try to set the `broker` value to 1 in either the configuration file or from the command line, helm still deploys 3 replicas.

```
helm install --debug --dry-run --name eventq --set broker=1 confluentinc/cp-helm-charts
...
---
# Source: cp-helm-charts/charts/cp-kafka/templates/statefulset.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: eventq-cp-kafka
  labels:
    app: cp-kafka
    chart: cp-kafka-0.1.0
    release: eventq
    heritage: Tiller
spec:
  serviceName: eventq-cp-kafka-headless
  podManagementPolicy: OrderedReady
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cp-kafka
        release: eventq
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5556"
    spec:
```
