### ISSUE TITLE
How to start a kafka-connect with ElasticSearch connector?

### ISSUE THREAD

**Issue by kcatstack** [confluentinc/cp-helm-charts#303]
Hi,
I want to start a kafka-connect only cluster (We already had kafka, schema-registry, i.e. installed some where else). We only need a kafka-connect to get data from that kafka to ElasticSearch.
How should I go about configuring to get this? Below is my current config. I can get the kafka-connect worker up and running but I don't know how to apply and start the ES connector:

```
# values.yaml
cp-zookeeper:
  enabled: false

cp-kafka:
  enabled: false

cp-schema-registry:
  enabled: false

cp-kafka-rest:
  enabled: false

cp-ksql-server:
  enabled: false

cp-control-center:
  enabled: false

cp-kafka-connect:
  enabled: true
  replicaCount: 1
  image: confluentinc/cp-kafka-connect
  imageTag: 5.2.2
  resources: {}
  ## If you do want to specify resources, uncomment the following lines, adjust them as necessary,
  ## and remove the curly braces after 'resources:'
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi
  configurationOverrides:
  "plugin.path": "/usr/share/java"
  "key.converter": "io.confluent.connect.avro.AvroConverter"
  "value.converter": "io.confluent.connect.avro.AvroConverter"
  "key.converter.schemas.enable": "false"
  "value.converter.schemas.enable": "false"
  "internal.key.converter": "org.apache.kafka.connect.json.JsonConverter"
  "internal.value.converter": "org.apache.kafka.connect.json.JsonConverter"
  "config.storage.replication.factor": "3"
  "offset.storage.replication.factor": "3"
  "status.storage.replication.factor": "3"
  kafka:
    bootstrapServers: "<my-kafka-server>"
  cp-schema-registry:
    url: "<my-schema-registry>"
```
