### ISSUE TITLE
Kafka-REST Config

### ISSUE THREAD

**Issue by brunodomenici** [confluentinc/cp-helm-charts#310]
Hi,

How to correctly pass ENV vars (or properties) to cp-kafka-rest helm chart? I don’t see values like configurationOverrides we have in cp-kafka-connect.

Thank you

**Comment by brunodomenici** [comment]
I'm able to configure (with help of Slack Community) with:

````
...
cp-kafka-rest:
  cp-zookeeper:
    url: null
  configurationOverrides:
    id: "kafka-rest"
    bootstrap.servers: "<ommited>:9092"
...
````

But HELM keeps including the ENV:

`
KAFKA_REST_ZOOKEEPER_CONNECT=kafka-rest-cp-zookeeper-headless:2181
`

But I don't have Zookeeper exposed in my Broker env.

I've tried with cp-kafka-rest:
````
  cp-zookeeper:
    url: null
````

````
  cp-zookeeper:
    url: ""
````

And without.

Thank you.
