### ISSUE TITLE
liveness and readiness for schema registry

### ISSUE THREAD

**Issue by HungUnicorn** [confluentinc/cp-helm-charts#393]
There is no liveness and readiness for schema registry, so there is downtime when deploying.

Here is what I use:
```
livenessProbe:
            tcpSocket:
              port: schema-registry
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /config
              port: schema-registry
            initialDelaySeconds: 100
```
`initialDelaySeconds` is required because schema registry has to read kafka topic into memory.

Please lemme know if MR is welcome.
