### ISSUE TITLE
Add annotations to cp-schema-registry service

### ISSUE THREAD

**Issue by mbrembilla** [confluentinc/cp-helm-charts#394]
Hi,
I think that it would be nice to have the possibility to add annotations in the service of the schema-registry.
Something like this:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-schema-registry.fullname" . }}
  labels:
    app: {{ template "cp-schema-registry.name" . }}
    chart: {{ template "cp-schema-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: schema-registry
      port: {{ .Values.servicePort }}
  selector:
    app: {{ template "cp-schema-registry.name" . }}
    release: {{ .Release.Name }}
```

Regards
Mauro
