### ISSUE TITLE
How to disable logs?

### ISSUE THREAD

**Issue by donton17** [confluentinc/cp-helm-charts#459]
I have started cp-helm-charts with a default persistence volume of 5 GB. After several days it will be getting full.
I was at " /opt/kafka/data-0/logs" dir. And I found that "_confluent-monitoring" took 2GB, And "_confluent-controlcenter" took 2.5GB. I think these logs are not needed. And we don't have any property for the cleanup control-center's log.

**Comment by mr-flannery** [comment]
I used the following workaround: If you take a look at the stateful set that is deployed for the broker pods, there's the following environment variable:

```yaml
Containers:
  cp-kafka-broker:
    Environment:
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
```

Removing this variable seems to have solved the problem for me (though I haven't yet observed it for the whole period that it took before for the brokers to exhaust the disk). You could also remove it from  `charts/cp-kafka/templates/statefulset.yaml` before installing the chart.

Not sure if this is a good idea or whether it has other unwanted consequences.
