### ISSUE TITLE
[Kubernetes and nodePort] Help acessing the brokers from my local machine 

### ISSUE THREAD

**Issue by thiagoananias** [confluentinc/cp-helm-charts#489]
Hello!

I have installed the confluent chart on a Kubernetes Cluster on AWS

`helm install kafka-confluent confluentinc/cp-helm-charts -f monitoring/kafka-confluent.yaml

The file
```
cp-control-center:
  enabled: false

cp-kafka:
  persistence:
    size: 30Gi
  configurationOverrides:
    "log.retention.hours": 48
    "advertised.listeners": |-
     EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))
    "listener.security.protocol.map": |-
     PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
  nodeport:
    enabled: true
    servicePort: 19092
    firstListenerPort: 31090
```

The SVC's 
NAME                                    TYPE      
kafka-confluent-cp-kafka                ClusterIP  
kafka-confluent-cp-kafka-0-nodeport     NodePort 
kafka-confluent-cp-kafka-1-nodeport     NodePort 
kafka-confluent-cp-kafka-2-nodeport     NodePort
kafka-confluent-cp-kafka-connect        ClusterIP
kafka-confluent-cp-kafka-headless       ClusterIP
kafka-confluent-cp-kafka-rest           ClusterIP
kafka-confluent-cp-ksql-server          ClusterIP
kafka-confluent-cp-schema-registry      ClusterIP
kafka-confluent-cp-zookeeper            ClusterIP
kafka-confluent-cp-zookeeper-headless   ClusterIP

All is working properly, but how can i access with a client on my machine? I'm trying to use port-forward on the three NodePort services but is not working... can you guys help me?

```
'use strict';

const { Kafka, logLevel } = require('kafkajs');

const kafka = new Kafka({
  clientId: 'my-app',
  connectionTimeout: 1000,
  brokers: [
    'localhost:8080',
    'localhost:8081',
    'localhost:8082',  ],
});

```

Thanks!
