### ISSUE TITLE
Unable to configure sasl.jaas.config in values.yaml or deployment.yaml

### ISSUE THREAD

**Issue by notrocketscience1** [confluentinc/cp-helm-charts#500]
Tried following things in both the files:

1. In values.yaml under kafka:
```
kafka:
  bootstrapServers: "xxxx:9092"
  sasl.mechanism: "PLAIN"
  sasl.jaas.config": 'org.apache.kafka.common.security.plain.PlainLoginModule required username="xxxx" password="xxxx";'
  security.protocol": "SASL_PLAINTEXT"
```

2. In values.yaml under kafka:
```
kafka:
  bootstrapServers: "xxxx:9092"
  consumer.sasl.mechanism: "PLAIN"
  consumer.sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="xxxx" password="xxxx";'
  consumer.security.protocol": "SASL_PLAINTEXT"
```

3. In values.yaml under configurationOverrides:
```
configurationOverrides:
  "consumer.sasl.mechanism": "PLAIN"
  "consumer.sasl.jaas.config": 'org.apache.kafka.common.security.plain.PlainLoginModule required username="xxxx" password="xxxx";'
  "consumer.security.protocol": "SASL_PLAINTEXT"
```

4. In values.yaml under configurationOverrides:
```
configurationOverrides:
  "sasl.mechanism": "PLAIN"
  "sasl.jaas.config": 'org.apache.kafka.common.security.plain.PlainLoginModule required username="xxxx" password="xxxx";'
  "security.protocol": "SASL_PLAINTEXT"
```

5. In deployment.yaml under env:
```
env:
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: {{ template "cp-control-center.kafka.bootstrapServers" . }}
            - name: SASL_MECHANISM
              value: PLAIN
            - name: SASL_JAAS_CONFIG
              value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="xxxx" password="xxxx";'
```
6. In deployment.yaml under env:
```
env:
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: {{ template "cp-control-center.kafka.bootstrapServers" . }}
            - name: CONTROL_CENTER_SASL_MECHANISM
              value: PLAIN
            - name: CONTROL_CENTER_SASL_JAAS_CONFIG
              value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="xxxx" password="xxxx";'
```

We are able to see the below in all 6 scenarios environment variables set to the k8s container but none of the values actually reflect during connection. 
```
printenv:

[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka startkubectl exec -it chart-1614894397-cp-control-center-5f48744d98-vnvgm -n kafka-test /bin/bashsktop\kafka\kafka-confluent\cp-control-center>[appuser@chart-1614894397-cp-control-center-5f48744d98-vnvgm ~]$ printenv
CONTROL_CENTER_CONSUMER_SECURITY_PROTOCOL=SASL_PLAINTEXT
CONTROL_CENTER_CONSUMER_SASL_MECHANISM=PLAIN
SASL_MECHANISM=PLAIN
SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="xxxx" password="xxxx";
CHART_1614894397_CP_CONTROL_CENTER_SERVICE_PORT_CC_HTTP=9021
CHART_1614894397_CP_CONTROL_CENTER_PORT_9021_TCP_PORT=9021
CHART_1614894397_CP_CONTROL_CENTER_PORT_9021_TCP_PROTO=tcp
CHART_1614894397_CP_CONTROL_CENTER_PORT_9021_TCP_ADDR=x.x.x.x
CONTROL_CENTER_REST_LISTENERS=http://0.0.0.0:9021
_=/usr/bin/printenv
[appuser@chart-1614894397-cp-control-center-5f48744d98-vnvgm ~]$ exit

```

Error occurred:

```
[main] INFO org.apache.kafka.clients.admin.AdminClientConfig - AdminClientConfig values: 
        bootstrap.servers = [xxxx:9092]
        client.dns.lookup = use_all_dns_ips
        client.id =
        connections.max.idle.ms = 300000
        default.api.timeout.ms = 60000
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        receive.buffer.bytes = 65536
        reconnect.backoff.max.ms = 1000
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 2147483647
        retry.backoff.ms = 100
        sasl.client.callback.handler.class = null
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.login.callback.handler.class = null
        sasl.login.class = null
        sasl.login.refresh.buffer.seconds = 300
        sasl.login.refresh.min.period.seconds = 60
        sasl.login.refresh.window.factor = 0.8
        sasl.login.refresh.window.jitter = 0.05
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        security.providers = null
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
        ssl.endpoint.identification.algorithm = https
        ssl.engine.factory.class = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLSv1.3
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS

[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka version: 6.0.1-ccs
[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka commitId: 9c1fbb3db1e0d69d
[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka startTimeMs: 1614894408456
[kafka-admin-client-thread | adminclient-1] INFO org.apache.kafka.clients.admin.internals.AdminMetadataManager - [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1614894438465, tries=1, nextAllowedTryMs=1614894438566) timed out at 1614894438466 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
[kafka-admin-client-thread | adminclient-1] INFO org.apache.kafka.clients.admin.internals.AdminMetadataManager - [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1614894678473, tries=1, nextAllowedTryMs=1614894678574) timed out at 1614894678474 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment
```

**sasl jaas config was never set and always 'null' during all the 6 scenarios.**
