### ISSUE TITLE
Cluster doesn't fully start

### ISSUE THREAD

**Issue by arashnikoo** [confluentinc/cp-helm-charts#503]
I'm trying to run the cluster on Rancher. Here is my helm values:

```
cp-control-center:
  enabled: true
  heapOptions: '-Xms512M -Xmx512M'
  image: confluentinc/cp-enterprise-control-center
  imagePullSecrets: null
  imageTag: 6.0.1
  resources: {}
cp-kafka:
  brokers: 1
  enabled: true
  heapOptions: '-Xms512M -Xmx512M'
  image: confluentinc/cp-enterprise-kafka
  imagePullSecrets: null
  imageTag: 6.0.1
  persistence:
    disksPerBroker: 1
    enabled: true
    size: 1Gi
  resources: {}
  securityContext:
    runAsUser: 0
cp-kafka-connect:
  enabled: true
  heapOptions: '-Xms512M -Xmx512M'
  image: confluentinc/cp-kafka-connect
  imagePullSecrets: null
  imageTag: 6.0.1
  resources: {}
cp-kafka-rest:
  enabled: true
  heapOptions: '-Xms512M -Xmx512M'
  image: confluentinc/cp-kafka-rest
  imagePullSecrets: null
  imageTag: 6.0.1
  resources: {}
cp-ksql-server:
  enabled: false
  heapOptions: '-Xms512M -Xmx512M'
  image: confluentinc/cp-ksqldb-server
  imagePullSecrets: null
  imageTag: 6.0.1
  ksql:
    headless: false
cp-schema-registry:
  enabled: true
  heapOptions: '-Xms512M -Xmx512M'
  image: confluentinc/cp-schema-registry
  imagePullSecrets: null
  imageTag: 6.0.1
  resources: {}
cp-zookeeper:
  enabled: true
  heapOptions: '-Xms512M -Xmx512M'
  image: confluentinc/cp-zookeeper
  imagePullSecrets: null
  imageTag: 6.0.1
  persistence:
    dataDirSize: 1Gi
    dataLogDirSize: 1Gi
    enabled: true
  resources: {}
  securityContext:
    runAsUser: 0
  servers: 1
global:
  systemDefaultRegistry: ''
```

This Pod is failing which I believe is causing the entire cluster not to full start:
Pod: cp-kafka-0

`

[2021-03-07 23:19:15,723] WARN Couldn't resolve server PLAINTEXT://cp-kafka-cp-kafka-headless:9092 from bootstrap.servers as DNS resolution failed for cp-kafka-cp-kafka-headless (org.apache.kafka.clients.ClientUtils)
--
Sun, Mar 7 2021 3:19:15 pm | [2021-03-07 23:19:15,723] INFO [Producer clientId=confluent-metrics-reporter] Closing the Kafka producer with timeoutMillis = 0 ms. (org.apache.kafka.clients.producer.KafkaProducer)
Sun, Mar 7 2021 3:19:15 pm | [2021-03-07 23:19:15,747] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)

`
