### ISSUE TITLE
Custom Kafka connect jmx config

### ISSUE THREAD

**Issue by ducminhle** [confluentinc/cp-helm-charts#504]
Hi All,

When I use cp-helm-charts, I use our own kafka-connect images, it builds from image `confluentinc/cp-kafka-connect` but we install some plugin from Confluent hub (for example Debezium-MySQL, Debezium-PostgreSQL, ...). 
We need to get metrics (example: Debezium) we need to change configmap Kafka connect jmx, but cp-helm-charts didn't support this feature. Could we add a feature custom Kafka connect jmx config for cp-helm-charts?
Thank you

**Comment by OneCricketeer** [comment]
Can you give an example of what metrics you're interested in and what configurations you're trying to modify that cannot be placed in your image?

**Comment by ducminhle** [comment]
Dockerfile:
```
FROM confluentinc/cp-kafka-connect:6.1.0
RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:1.4.0
RUN confluent-hub install --no-prompt debezium/debezium-connector-mysql:1.4.0
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3:5.5.3
```
About metrics I customize jmx config to:
```
jmx-kafka-connect-prometheus.yml: |                                                                                                                                                                        
     jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi                                                                                                                                              
     lowercaseOutputName: false                                                                                                                                                                               
     lowercaseOutputLabelNames: false                                                                                                                                                                         
     ssl: false                                                                                                                                                                                               
     rules:                                                                                                                                                                                                   
     - pattern : "kafka.connect<type=connect-worker-metrics>([^:]+):"                                                                                                                                         
       name: "cp_kafka_connect_connect_worker_metrics_$1"                                                                                                                                                     
     - pattern : "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"                                                                                                                            
       name: "cp_kafka_connect_connect_metrics_$1_$2"                                                                                                                                                         
     - pattern : "kafka.connect<type=connector-task-metrics, connector=([^:]+), task=([^:]+)><>status: ([^:]+)"                                                                                               
       name: "cp_kafka_connect_connect_connector_metrics"                                                                                                                                                     
       value: 1                                                                                                                                                                                               
       labels:                                                                                                                                                                                                
         connector: $1                                                                                                                                                                                        
         task: $2                                                                                                                                                                                             
         status: $3                                                                                                                                                                                           
     - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), key=([^>]+)><>RowsScanned"                                                                                         
       name: "debezium_metrics_RowsScanned"                                                                                                                                                                   
       labels:                                                                                                                                                                                                
         plugin: "$1"                                                                                                                                                                                         
         name: "$3"                                                                                                                                                                                           
         context: "$2"                                                                                                                                                                                        
         table: "$4"                                                                                                                                                                                          
     - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^>]+)>([^:]+)"                                                                                                            
       name: "debezium_metrics_$4"                                                                                                                                                                            
       labels:                                                                                                                                                                                                
         plugin: "$1"                                                                                                                                                                                         
         name: "$3"                                                                                                                                                                                           
         context: "$2"                                                                                                                                                                                        
     - pattern: 'java.lang<type=Memory><(\w+)MemoryUsage>(\w+): (\d+)'                                                                                                                                        
       name: jvm_memory_bytes_$2                                                                                                                                                                              
       labels:                                                                                                                                                                                                
         area: "$1"                                                                                                                                                                                           
       value: $3                                                                                                                                                                                              
       type: GAUGE                                                                                                                                                                                            
     - pattern: "java.lang<type=Threading><>(\\w+)"                                                                                                                                                           
       name: "jvm_threads_$1"
```
