### ISSUE TITLE
NodePort support should be added

### ISSUE THREAD

**Issue by survivant** [confluentinc/cp-helm-charts#510]
all the charts should have something like this in values.yaml

````
service:
  # type: NodePort
  # if you want to force a specific nodePort. Must be use with service.type=NodePort
  # nodePort:
````

in service.yaml (as example)

````
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") .Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

````
