### ISSUE TITLE
helm values for a Developer licensed cluster

### ISSUE THREAD

**Issue by tuxerrante** [confluentinc/cp-helm-charts#545]
Hi,
I'm trying to setup a Confluent cluster in a non-enterprise configuration.
I've tried different options, changing both the number of kafka broker replicas to 1 and the kafka image itself, but everything seems to end in a crashLoopBackoff of the pods.

What I did here was to apply the helm values taken from this repo, and
-    disable the control center 
-    set kafka image on cp-kafka with 1 replica

Applied with this command:
    helm install -f confluent-cp-helm-values.yaml confluent confluentinc/cp-helm-charts --namespace confluent

```
## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  enabled: true
  servers: 3
  image: confluentinc/cp-zookeeper
  imageTag: 6.2.0
  heapOptions: "-Xms512M -Xmx512M"
  persistence:
    enabled: true
    dataDirSize: 10Gi
    dataDirStorageClass: "oci-bv"
snaphots.
    dataLogDirSize: 10Gi
    dataLogDirStorageClass: "oci-bv"
  securityContext: 
    runAsUser: 0
  resources: {}
## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
cp-kafka:
  enabled: true
  brokers: 1                        # NO MORE THAN ONE REPLICAS IS ALLOWED FOR DEVELOPER LICENSE
  image: confluentinc/cp-kafka
  imageTag: 6.2.0
  heapOptions: "-Xms512M -Xmx512M"
  persistence:
    enabled: true
    storageClass: "oci-bv"
    size: 5Gi
    disksPerBroker: 1
  resources: {}
  securityContext: 
    runAsUser: 0

## ------------------------------------------------------
## Schema Registry
## ------------------------------------------------------
cp-schema-registry:
  enabled: true
  image: confluentinc/cp-schema-registry
  imageTag: 6.2.0
  imagePullSecrets:
  #  - name: "regcred"
  heapOptions: "-Xms512M -Xmx512M"
  resources: {}

## ------------------------------------------------------
## REST Proxy
## ------------------------------------------------------
cp-kafka-rest:
  enabled: true
  image: confluentinc/cp-kafka-rest
  imageTag: 6.2.0
  heapOptions: "-Xms512M -Xmx512M"
  resources: {}

## ------------------------------------------------------
## Kafka Connect
## ------------------------------------------------------
cp-kafka-connect:
  enabled: true
  image: confluentinc/cp-kafka-connect
  imageTag: 6.2.0
  heapOptions: "-Xms512M -Xmx512M"
  resources: {}

## ------------------------------------------------------
## KSQL Server
## ------------------------------------------------------
cp-ksql-server:
  enabled: true
  image: confluentinc/cp-ksqldb-server
  imageTag: 6.2.0
  heapOptions: "-Xms512M -Xmx512M"
  ksql:
    headless: false

## ------------------------------------------------------
## Control Center
## ------------------------------------------------------
cp-control-center:
  enabled: false
  image: confluentinc/cp-enterprise-control-center
  imageTag: 6.2.0
  heapOptions: "-Xms512M -Xmx512M"
  resources: {}

```

It seems they can't see each other, for example trying to reach "confluent-cp-kafka-0.confluent-cp-kafka-headless.confluent:9092" the kafka broker fails.

![immagine](https://user-images.githubusercontent.com/8364469/125101325-63652f00-e0da-11eb-83f9-8a4391e7fb1b.png)
