### ISSUE TITLE
NodePort service.yaml for cp-kafka uses incorrect value for targetPort

### ISSUE THREAD

**Issue by fbascheper** [confluentinc/cp-helm-charts#562]
The `nodeport-service.yaml` file in cp-kafka/templates contains an incorrect value for targetPort. 
According to [the NodePort definition from kubernetes.io](https://kubernetes.io/docs/concepts/services-networking/service/) by default and for convenience, the `targetPort` is set to the same value as the `port` field for a NodePort.

However, in  `nodeport-service.yaml`, I see the following
```yaml
spec:
  type: NodePort
  ports:
    - name: external-broker
      port: {{ $servicePort }}
      targetPort: {{ $externalListenerPort }}
      nodePort: {{ $externalListenerPort }}
      protocol: TCP
```

This should be changed to
```yaml
spec:
  type: NodePort
  ports:
    - name: external-broker
      port: {{ $servicePort }}
      targetPort: {{ $servicePort }}
      nodePort: {{ $externalListenerPort }}
      protocol: TCP
```

After this change, all nodeports were functioning OK for us.
