### ISSUE TITLE
Topic messages disappears

### ISSUE THREAD

**Issue by MaratFaskhiev** [confluentinc/cp-helm-charts#563]
Hi.

I have an issue described here on all browsers which I tested:

https://docs.confluent.io/platform/current/control-center/installation/troubleshooting.html#cannot-browse-topic-messages-using-safari-and-authentication

It occurs in Chrome, Firefox and Edge.

I'm able to view messages for a while. But eventually "An known error has occured. Check the connection settings appears." message replaces the message list. And I can view topic messages again only after browser page refresh:
![error](https://user-images.githubusercontent.com/1787520/137680205-49532b77-c5a5-4505-aaad-6636377aa198.png)

Here is my yaml which I'm using for the testing purposes:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app-confluent-qa
  namespace: qa
spec:
  releaseName: app-confluent-qa
  chart:
    repository: https://confluentinc.github.io/cp-helm-charts/
    name: cp-helm-charts
    version: 0.6.1
  values:
    cp-zookeeper:
      servers: 1
      heapOptions: "-Xms256M -Xmx256M"
      persistence:
        enabled: true
        dataDirStorageClass: "default"
        dataLogDirStorageClass: "default"
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
    cp-kafka:
      brokers: 1
      configurationOverrides:
        "offsets.topic.replication.factor": 1
        "default.replication.factor": 1
        "min.insync.replicas": 1
        "auto.create.topics.enable": true
      customEnv:
        CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      heapOptions: "-Xms256M -Xmx256M"
      persistence:
        enabled: true
        storageClass: "default"
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 1Gi
    cp-schema-registry:
      heapOptions: "-Xms256M -Xmx256M"
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
    cp-control-center:
      configurationOverrides:
        "replication.factor": 1
      customEnv:
        CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      heapOptions: "-Xms256M -Xmx256M"
      resources:
        limits:
          memory: 3Gi
        requests:
          cpu: 100m
          memory: 3Gi
    cp-kafka-rest:
      enabled: false
    cp-kafka-connect:
      enabled: false
    cp-ksql-server:
      enabled: false
```
