### ISSUE TITLE
Example of Schema Registry Helm chart with external Kafka, protected by authentication

### ISSUE THREAD

**Issue by skayred** [confluentinc/cp-helm-charts#577]
Hello,

is it possible to start Schema Registry together with already working Kafka installation? I have tried to following config:

```
sasl:
  scram:
    enabled: true
    clientUser: *
    clientPassword: *
prometheus:
  jmx:
    enabled: false
external:
  enabled: true
  type: NodePort
  nodePort: 30081
kafka:
  enabled: false
  bootstrapServers: kafka:9092
schemaRegistryOpts:
configurationOverrides:
  sasl:
    enabled: true
    mechanism: PLAIN
    jaas:
      config: org.apache.kafka.common.security.plain.PlainLoginModule required username="*" password="*";
  client:
    sasl:
      mechanism: PLAINTEXT
      protocol: SASL_SSL
      jaas:
        config: org.apache.kafka.common.security.plain.PlainLoginModule required username="*" password="*";
configurationOverrides:
  sasl:
    enabled: true
    mechanism: PLAIN
    jaas:
      config: org.apache.kafka.common.security.plain.PlainLoginModule required username="*" password="*";
  client:
    sasl:
      mechanism: PLAINTEXT
      protocol: SASL_SSL
      jaas:
        config: org.apache.kafka.common.security.plain.PlainLoginModule required username="*" password="*";
```

but seems like repository fails to start:

```
[main] INFO org.apache.kafka.clients.admin.AdminClientConfig - AdminClientConfig values:
	bootstrap.servers = [kafka:9092]
	client.dns.lookup = use_all_dns_ips
	client.id =
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 127000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS

[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka version: 6.1.0-ccs
[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka commitId: 5496d92defc9bbe4
[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka startTimeMs: 1640789871932
[kafka-admin-client-thread | adminclient-1] INFO org.apache.kafka.clients.admin.internals.AdminMetadataManager - [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1640789901942, tries=73, nextAllowedTryMs=1640789902043) timed out at 1640789901943 after 73 attempt(s)
Caused by: org.apache.kafka.common.errors.DisconnectException: Cancelled fetchMetadata request with correlation id 145 due to node -1 being disconnected
```

Could you provide any example of starting the registry with existing Kafka? I am trying to deploy Registry into the same namespace, where Kafka lives, according to the Registry logs, it doesn't pick up any of configs I am trying to override.
