### ISSUE TITLE
Chart does not work in Kubernetes 1.25. `PodDisruptionBudget` `v1beta` is _removed_ 

### ISSUE THREAD

**Issue by dhinojosa** [confluentinc/cp-helm-charts#620]
The chart no longer works in 1.25
The chart should use Helm's `Capabilities.` object to determine the version of Kubernetes and make the right `PodDisruptionBudget`.  The new reference is here: https://kubernetes.io/docs/tasks/run-application/configure-pdb/

I suspect this is what the new one should look like. 

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: confluent-oss-cp-zookeeper-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: cp-zookeeper
```
