### ISSUE TITLE
no option for schedulerName

### ISSUE THREAD

**Issue by senthil13** [confluentinc/cp-helm-charts#621]
We can't use the `default-scheduler`, but there is no option to select a different option. I specified in my value.yml, but still, the deployment is using the `default-scheduler`

```
## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  schedulerName: strok
  enabled: true
  servers: 3
  heapOptions: "-Xms512M -Xmx512M"
## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
cp-kafka:
  schedulerName: strok
  enabled: true
  brokers: 3
```
deployment.yaml
```
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
```

Thanks
Senthil
